name: TESuperCDK
main: TESuperCDK\CDK_Main
version: 1.0.0
api: 
  - 1.0.0
  - 2.0.0
  - 3.0.0
load: POSTWORLD
author: Teaclon

commands:
  tscdkhelp:
    description: Use Helper Command.
  tscdk:
    description: Modules Command.
